export type Property = {
  id: string; title: string; location: string; city: string; state: string; type: string; area: string; price: string; priceNum: number; image: string; verified: boolean; featured?: boolean; road: string; description: string
};

export const properties: Property[] = [
  {id:'p1',title:'Highway Touch Agricultural Land',location:'Tronica City, Ghaziabad',city:'Tronica City',state:'Uttar Pradesh',type:'Agricultural Land',area:'5 Bigha',price:'₹78 Lakh',priceNum:7800000,image:'/delhi-meerut.jpg',verified:true,featured:true,road:'45 ft road',description:'Agricultural parcel with quick access to Delhi–Meerut Expressway and Tronica City.'},
  {id:'p2',title:'Residential Plot Near Tronica City',location:'Tronica City, Ghaziabad',city:'Tronica City',state:'Uttar Pradesh',type:'Residential Plot',area:'2,400 sq.ft',price:'₹48 Lakh',priceNum:4800000,image:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',verified:true,featured:true,road:'30 ft road',description:'Ready residential plot close to local markets and the expressway corridor.'},
  {id:'p3',title:'Commercial Corner Plot',location:'Tronica City, Ghaziabad',city:'Tronica City',state:'Uttar Pradesh',type:'Commercial Plot',area:'1,800 sq.ft',price:'₹1.15 Cr',priceNum:11500000,image:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',verified:true,featured:true,road:'60 ft road',description:'Corner commercial opportunity with strong visibility and city connectivity.'},
  {id:'p4',title:'Industrial Land Near Corridor',location:'Tronica City, Ghaziabad',city:'Tronica City',state:'Uttar Pradesh',type:'Industrial Land',area:'1.5 Acre',price:'₹3.10 Cr',priceNum:31000000,image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',verified:true,featured:true,road:'80 ft road',description:'Industrial parcel positioned for logistics and manufacturing access.'},
  {id:'p5',title:'Farm Land Investment Plot',location:'Tronica City, Ghaziabad',city:'Tronica City',state:'Uttar Pradesh',type:'Farm Land',area:'8 Bigha',price:'₹1.05 Cr',priceNum:10500000,image:'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1200&q=80',verified:false,featured:true,road:'24 ft road',description:'Open farm land suitable for agriculture, farmhouse or long-term investment.'},
  {id:'p6',title:'Budget Land Near City Edge',location:'Loni, Ghaziabad',city:'Loni',state:'Uttar Pradesh',type:'Agricultural Land',area:'3 Bigha',price:'₹42 Lakh',priceNum:4200000,image:'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1200&q=80',verified:false,featured:true,road:'20 ft road',description:'Affordable land option with road access and nearby residential growth.'},
  {id:'p7',title:'Expressway Facing Residential Plot',location:'Ghaziabad, Uttar Pradesh',city:'Ghaziabad',state:'Uttar Pradesh',type:'Residential Plot',area:'3,000 sq.ft',price:'₹62 Lakh',priceNum:6200000,image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',verified:true,featured:true,road:'40 ft road',description:'Residential plot with strong connectivity towards NCR and Eastern Peripheral Expressway.'},
  {id:'p8',title:'Eastern Peripheral Commercial Land',location:'Ghaziabad, Uttar Pradesh',city:'Ghaziabad',state:'Uttar Pradesh',type:'Commercial Plot',area:'4,000 sq.ft',price:'₹1.85 Cr',priceNum:18500000,image:'/eastern-peripheral.jpg',verified:true,featured:true,road:'60 ft road',description:'Commercial parcel near the Eastern Peripheral Expressway growth belt.'},
  {id:'p9',title:'Baghpat Agricultural Opportunity',location:'Baghpat, Uttar Pradesh',city:'Baghpat',state:'Uttar Pradesh',type:'Agricultural Land',area:'10 Bigha',price:'₹92 Lakh',priceNum:9200000,image:'/delhi-dehradun.jpg',verified:true,featured:true,road:'30 ft road',description:'Large agricultural parcel with access towards Delhi–Dehradun Expressway.'},
  {id:'p10',title:'NCR Farmhouse Plot',location:'Greater Noida, Uttar Pradesh',city:'Greater Noida',state:'Uttar Pradesh',type:'Farm Land',area:'6 Bigha',price:'₹1.10 Cr',priceNum:11000000,image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80',verified:true,featured:false,road:'30 ft road',description:'Farmhouse-friendly land in a growing NCR location.'}
];

export const cities = ['Tronica City','Ghaziabad','Loni','Baghpat','Greater Noida','Noida','Delhi'];
export const states = ['Uttar Pradesh','Delhi'];
